# Generated by Django 5.2.12 on 2026-03-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fitnessperformance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='activity_record',
            field=models.TextField(blank=True, help_text='Record of physical activities', null=True),
        ),
    ]
