# Generated by Cascade on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_academicterm_fitnesstestparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
