# Generated by Django 5.2.12 on 2026-03-13 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(db_index=True, max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['section'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['section'], name='api_student_section_edcff6_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['teacher'], name='api_student_teacher_3c85a9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['section', 'teacher'], name='api_student_section_320f3b_idx'),
        ),
        migrations.AddField(
            model_name='teachersection',
            name='assigned_by',
            field=models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachersection',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teachersection',
            unique_together={('teacher', 'section')},
        ),
    ]
