# Generated by Django 5.2.12 on 2026-03-13 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_teachersection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PESession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Session name or topic', max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('section', models.CharField(db_index=True, help_text='Class/section for this session', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Session description or activities')),
                ('start_time', models.TimeField(help_text='Session start time')),
                ('end_time', models.TimeField(help_text='Session end time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='pe_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused'), ('LATE', 'Late')], default='PRESENT', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about attendance')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.pesession')),
            ],
            options={
                'ordering': ['-marked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pesession',
            index=models.Index(fields=['date', 'section'], name='api_pesessi_date_6daf86_idx'),
        ),
        migrations.AddIndex(
            model_name='pesession',
            index=models.Index(fields=['teacher', 'date'], name='api_pesessi_teacher_50ed9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pesession',
            unique_together={('date', 'section', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['session', 'status'], name='api_attenda_session_4d4627_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'marked_at'], name='api_attenda_student_a73678_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status', 'marked_at'], name='api_attenda_status_912e3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'session')},
        ),
    ]
